{% set name = "arraykit" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arraykit-{{ version }}.tar.gz
  sha256: eb39a4bbd42e6d7cce7dec773f84425b3dfcd6bc155e20118b4e711d66409024

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - setuptools
    - python
    - pip
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - arraykit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/static-frame/arraykit
  summary: Array utilities for StaticFrame
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - flexatone
    - chaburkland
